### ISSUE TITLE
pika.exceptions.ConnectionClosed: failed: timeout

### ISSUE THREAD

**Issue by lee212** [radical-collaboration/MDFF-EnTK#21]
Ben reported this issue on last Friday, the connection issue,:
```
EnTK session: re.session.login2.benjha.018516.0002
Creating AppManagerSetting up RabbitMQ system                                 ok
                                                                              ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                   n/a
new session: [re.session.login2.benjha.018516.0002]                            \
database   : [mongodb://admin:****@apps.marble.ccs.ornl.gov:32767/test]       ok
create pilot manager                                                          ok
submit 1 pilot(s)
        pilot.0000   ornl.summit             168 cores       0 gpus           ok
All components created
create unit managerUpdate: simple-mdff state: SCHEDULING
Update: simple-mdff.Generating a simulated density map state: SCHEDULING
Update: simple-mdff.Generating a simulated density map.Starting to load the target PDB state: SCHEDULING
Update: simple-mdff.Generating a simulated density map.Starting to load the target PDB state: SCHEDULED
Update: simple-mdff.Generating a simulated density map state: SCHEDULED
/gpfs/alpine/world-shared/bip115/radical_tools_python/entk_1.5.1/lib/python3.7/site-packages/pymongo/topology.py:162: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe
  "MongoClient opened before fork. Create MongoClient only "
                                                           ok
submit: ########################################################################
Update: simple-mdff.Generating a simulated density map.Starting to load the target PDB state: SUBMITTING
Exception in thread dequeue-thread:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/alpine/world-shared/bip115/radical_tools_python/entk_1.5.1/lib/python3.7/site-packages/radical/entk/appman/wfprocessor.py", line 431, in _dequeue
    mq_connection = pika.BlockingConnection(self._rmq_conn_params)
  File "/gpfs/alpine/world-shared/bip115/radical_tools_python/entk_1.5.1/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 377, in __init__
    self._process_io_for_connection_setup()
  File "/gpfs/alpine/world-shared/bip115/radical_tools_python/entk_1.5.1/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 417, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/gpfs/alpine/world-shared/bip115/radical_tools_python/entk_1.5.1/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 471, in _flush_output
    raise exceptions.ConnectionClosed(maybe_exception)
pika.exceptions.ConnectionClosed: Connection to 128.219.132.38:30256 failed: timeout
Update: simple-mdff.Generating a simulated density map.Starting to load the target PDB state: EXECUTED
Update: simple-mdff.Generating a simulated density map.Starting to load the target PDB state: DONE
Update: simple-mdff.Generating a simulated density map state: DONE
Update: simple-mdff.Converting the density map to an MDFF potential state: SCHEDULING
Update: simple-mdff.Converting the density map to an MDFF potential.generate dx file state: SCHEDULING
Update: simple-mdff.Converting the density map to an MDFF potential.generate dx file state: SCHEDULED
Update: simple-mdff.Converting the density map to an MDFF potential state: SCHEDULED
submit: ########################################################################
Update: simple-mdff.Converting the density map to an MDFF potential.generate dx file state: SUBMITTING
Update: simple-mdff.Converting the density map to an MDFF potential.generate dx file state: DONE
Update: simple-mdff.Converting the density map to an MDFF potential state: DONE
Update: simple-mdff.Preparing the initial structure state: SCHEDULING
Update: simple-mdff.Preparing the initial structure.Starting to load the initial structure state: SCHEDULING
Update: simple-mdff.Preparing the initial structure.Starting to load the initial structure state: SCHEDULED
Update: simple-mdff.Preparing the initial structure state: SCHEDULED
submit: ########################################################################
Update: simple-mdff.Preparing the initial structure.Starting to load the initial structure state: SUBMITTING
Update: simple-mdff.Preparing the initial structure.Starting to load the initial structure state: EXECUTED
Update: simple-mdff.Preparing the initial structure.Starting to load the initial structure state: DONE
Update: simple-mdff.Preparing the initial structure state: DONE
Update: simple-mdff.Defining secondary structure restraints state: SCHEDULING
Update: simple-mdff.Defining secondary structure restraints.task.0003 state: SCHEDULING
Update: simple-mdff.Defining secondary structure restraints.task.0003 state: SCHEDULED
Update: simple-mdff.Defining secondary structure restraints state: SCHEDULED
submit: ########################################################################
Update: simple-mdff.Defining secondary structure restraints.task.0003 state: SUBMITTING
Update: simple-mdff.Defining secondary structure restraints.task.0003 state: DONE
Update: simple-mdff.Defining secondary structure restraints state: DONE
Update: simple-mdff.cispeptide and chirality restraints state: SCHEDULING
Update: simple-mdff.cispeptide and chirality restraints.task.0004 state: SCHEDULING
Update: simple-mdff.cispeptide and chirality restraints.task.0004 state: SCHEDULED
Update: simple-mdff.cispeptide and chirality restraints state: SCHEDULED
close unit manager                                                            ok
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/gpfs/alpine/world-shared/bip115/radical_tools_python/entk_1.5.1/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 308, in _process_tasks
    mq_connection = pika.BlockingConnection(rmq_conn_params)
  File "/gpfs/alpine/world-shared/bip115/radical_tools_python/entk_1.5.1/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 377, in __init__
    self._process_io_for_connection_setup()
  File "/gpfs/alpine/world-shared/bip115/radical_tools_python/entk_1.5.1/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 417, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/gpfs/alpine/world-shared/bip115/radical_tools_python/entk_1.5.1/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 471, in _flush_output
    raise exceptions.ConnectionClosed(maybe_exception)
pika.exceptions.ConnectionClosed: Connection to 128.219.132.38:30256 failed: timeout
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/alpine/world-shared/bip115/radical_tools_python/entk_1.5.1/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 331, in _process_tasks
    raise EnTKError(e) from e
radical.entk.exceptions.EnTKError: Connection to 128.219.132.38:30256 failed: timeout
```

This error produced with the Slate info:
```
export RADICAL_PILOT_DBURL="mongodb://***@apps.marble.ccs.ornl.gov:32767/***"
export RMQ_HOSTNAME="apps.marble.ccs.ornl.gov"
export RMQ_PORT="30256"
```

While the slate service is unavailable, I recommend using the one we provided, (over the slack).

Luckily, my test run on today finished all stages as expected,:
```
...: DONE
Update: simple-mdff.Calculating the cross-correlation coefficient state: DONE
Update: simple-mdff state: DONE
close unit manager                                                            ok
wait for 1 pilot(s)
              0                                                               ok
closing session re.session.login5.hrlee.018520.0000                            \
close pilot manager                                                            \
wait for 1 pilot(s)
              0                                                               ok
                                                                              ok
session lifetime: 282.2s                                                      ok
All components terminated
```

**Comment by lee212** [comment]
@wilkinson, could you check if the db/rabbitmq service is running okay? I tried to use but got connection timed out error.

**Comment by benjha** [comment]
@wilkinson,  
Slate is enabled per project right ?, so if its disabled for BIP115,  can jobs running with BIP115 account  "see" those servers ? 

@lee212 What project account were you  using that worked ? Is Slate enabled for that account ?

**Comment by lee212** [comment]
I ran a test with `csc393` and csc393 has a Slate account although there is no deployed service under the account. With my earlier experience with Slate, my runs were able to get access to the Slate outside of the project, if policy/rules remain same.

**Comment by wilkinson** [comment]
@lee212, my non-EnTK demos on Summit that use MongoDB are not running tonight (timeout), but the RabbitMQ demos are running correctly on the login nodes, batch nodes, and compute nodes. I'm not sure why MongoDB is not running, though, because someone must have changed a cluster policy on Marble -- the web GUI says "You don't have access to this section due to cluster policy." I'll have to inquire about that separately.

In the meantime, maybe we need to deploy these services specifically for BIP115. I do not have access to that project itself, so either I can be added or else I can send the directions needed to deploy those services.

@benjha, the services Hyungro was using are running on new Marble under STF011, because CSC393 was waiting for their account to be created. There's no reason BIP115 shouldn't also be able to use services deployed by STF011, since they just need user/password/port information.

**Comment by wilkinson** [comment]
I was wrong about the web GUI -- I had typed an incorrect URL, oops. The MongoDB pod is giving a "CrashLoopBackOff" error, but that isn't what this thread was about. Y'all were asking about RabbitMQ, which seems to be running correctly. I'm not sure what is wrong with MongoDB at the moment.

We should probably deploy this stuff under BIP115 so we can build in-place. When I debug on STF011, if I re-deploy, the ports will change, and that will break things for y'all in ways you won't be able to fix. I will apply for access to BIP115 to help expedite this process.

**Comment by lee212** [comment]
@wilkinson , if you could re-deploy mongodb, it would be helpful for me and others to run some tests. I think we can live with a new port number even if it changes.

**Comment by lee212** [comment]
With the mongodb deployed on other project, (not stf011), I don't have this connection issue anymore. I am closing this for now.
